// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kyxgzlucitqdgplwakqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt5eGd6bHVjaXRxZGdwbHdha3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIxNDY3MDgsImV4cCI6MjA3NzcyMjcwOH0.3NSFUBJf_98GO8l76N3xcd9pLyB7NUj5AnuI8P2belY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});